name: gql_phoenix_link_2
description: A graphql link using phoenix sockets
version: 0.5.0
homepage: https://github.com/redDwarf03/gql_phoenix_link.git

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  # PhoenixSocket provides a feature-complete implementation of Phoenix Sockets, using a single API based on StreamChannels compatible with any deployment of Flutter.
  phoenix_socket: ^0.5.3

  # Basis for GraphQL execution layer to support Link and Client.
  gql_exec: ^0.4.0

  # A simple and modular AST-based GraphQL request execution interface.
  gql_link: ^0.4.2

dev_dependencies:
  # Recommended lints for Flutter apps, packages, and plugins to encourage good coding practices.
  flutter_lints: ^1.0.4
  # Automatically organize your dart imports
  import_sorter: ^4.6.0
  # A full featured library for writing and running Dart tests across platforms.
  test: ^1.20.1
